# Generated by Django 2.2.4 on 2019-09-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190916_0016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcomment',
            old_name='method',
            new_name='article',
        ),
    ]
